class miError1(Exception):
    def __init__(self, msg):
        self.msg = msg
class miError2(Exception):
    pass

class miError3(Exception):
    pass

class miError4(Exception):
    pass

class miError5(Exception):
    def __init__(self, msg):
        self.msg = msg

def main():
    try:
        while(True):
            op = input("Digite la operacion que desea hacer: ")
            sep = " "
            op = op.split(sep)
            if op[1] == "+":
                print(int(op[0]) + int(op[2]))
            elif op[1] == "-":
                print(int(op[0]) - int(op[2]))
            elif op[1] == "*":
                print(int(op[0]) * int(op[2]))
            elif op[1] == "/":
                print(int(op[0]) / int(op[2]))
            elif op == "terminar":
                break
            elif op[1] == "**" or op[1] == "^":
                raise miError5("No se conoce esa operación")

    except ZeroDivisionError:
        raise miError1("Paila esa divididida por 0")
    except IndexError:
        raise miError2("Falto un número por digitar")
    except KeyboardInterrupt:
        raise miError3("Escriba 'terminar' preferiblemente ")
    except ValueError:
        raise miError4("Mal digitación de la operación")
    except miError5 as e:
        print(f"paila -> {e.msg}")
    except:
        ("Sucedio un error aun no definido")
        main()

main()
